export const Cuisines = [
  "African",
  "American",
  "British",
  "Cajun",
  "Caribbean",
  "Chinese",
  "Eastern European",
  "European",
  "French",
  "German",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Japanese",
  "Jewish",
  "Korean",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "Southern",
  "Spanish",
  "Thai",
  "Vietnamese",
];

export const Mealtype = [
  "main course",
  "side dish",
  "dessert",
  "appetizer",
  "salad",
  "bread",
  "breakfast",
  "soup",
  "beverage",
  "sauce",
  "marinade",
  "fingerfood",
  "snack",
  "drink",
];

export const sampleRandom = {
  meals: [
    {
      idMeal: "52830",
      strMeal: "Crock Pot Chicken Baked Tacos",
      strDrinkAlternate: null,
      strCategory: "Chicken",
      strArea: "Mexican",
      strInstructions:
        "Put the uncooked chicken breasts in the crock pot. Pour the full bottle of salad dressing over the chicken. Sprinkle the rest of the ingredients over the top and mix them in a bit with a spoon.\r\nCover your crock pot with the lid and cook on high for 4 hours.\r\nRemove all the chicken breasts from the crock pot and let cool.\r\nShred the chicken breasts and move to a glass bowl.\r\nPour most of the liquid over the shredded chicken.\r\nFOR THE TACOS:\r\nMake the guacamole sauce by mixing the avocado and green salsa together. Pour the guacamole mixture through a strainer until smooth and transfer to a squeeze bottle. Cut the tip off the lid of the squeeze bottle to make the opening more wide if needed.\r\nMake the sour cream sauce by mixing the sour cream and milk together until you get a more liquid sour cream sauce. Transfer to a squeeze bottle.\r\nIn a 9x 13 glass baking dish, fill all 12+ tacos with a layer of refried beans, cooked chicken and shredded cheese.\r\nBake at 450 for 10-15 minutes just until the cheese is melted and bubbling.\r\nOut of the oven top all the tacos with the sliced grape tomaotes, jalapeno and cilantro.\r\nFinish with a drizzle of guacamole and sour cream.\r\nEnjoy!",
      strMealThumb:
        "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
      strTags: null,
      strYoutube: "https://www.youtube.com/watch?v=oqL0mLDBzS4",
      strIngredient1: "Chicken Breasts",
      strIngredient2: "Vinaigrette Dressing",
      strIngredient3: "Cumin",
      strIngredient4: "Smoked Paprika",
      strIngredient5: "Garlic",
      strIngredient6: "Refried Beans",
      strIngredient7: "Hard Taco Shells",
      strIngredient8: "Shredded Mexican Cheese",
      strIngredient9: "Grape Tomatoes",
      strIngredient10: "Jalapeno",
      strIngredient11: "Avocado",
      strIngredient12: "Green Salsa",
      strIngredient13: "Sour Cream",
      strIngredient14: "Milk",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "4 - 6",
      strMeasure2: "1 bottle",
      strMeasure3: "1\u00bd tablespoon",
      strMeasure4: "1 tablespoon",
      strMeasure5: "1 teaspoon",
      strMeasure6: "1 can",
      strMeasure7: "12",
      strMeasure8: "2 cups",
      strMeasure9: "Halved",
      strMeasure10: "Sliced and Seeded",
      strMeasure11: "Peeled and Sliced",
      strMeasure12: "2 tablespoons",
      strMeasure13: "3 tablespoons",
      strMeasure14: "1 tablespoon",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
      strSource: "http://www.nobiggie.net/crock-pot-chicken-baked-tacos/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};
























// export const SampleResults = {
//   results: [
//     {
//       id: 782601,
//       title: "Red Kidney Bean Jambalaya",
//       image: "https://spoonacular.com/recipeImages/782601-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 648524,
//       title: "Jean's Seafood Gumbo",
//       image: "https://spoonacular.com/recipeImages/648524-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 648432,
//       title: "Jambalaya Stew",
//       image: "https://spoonacular.com/recipeImages/648432-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 659638,
//       title: "Seafood Gumbo",
//       image: "https://spoonacular.com/recipeImages/659638-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 636714,
//       title: "Cajun Cuisine: Vegan Jambalaya",
//       image: "https://spoonacular.com/recipeImages/636714-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 636732,
//       title: "Cajun Lobster Pasta",
//       image: "https://spoonacular.com/recipeImages/636732-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 715545,
//       title: "How to Make the Best Chicken Jambalaya",
//       image: "https://spoonacular.com/recipeImages/715545-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 636736,
//       title: "Cajun Seafood and Andouille Sausage Gumbo",
//       image: "https://spoonacular.com/recipeImages/636736-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 1055614,
//       title: "How to Make a Louisiana Style Gumbo",
//       image: "https://spoonacular.com/recipeImages/1055614-312x231.jpg",
//       imageType: "jpg",
//     },
//     {
//       id: 640166,
//       title:
//         "Cornmeal-Crusted Catfish with Cajun Seasoning and Spicy Tartar Sauce",
//       image: "https://spoonacular.com/recipeImages/640166-312x231.jpg",
//       imageType: "jpg",
//     },
//   ],
//   offset: 0,
//   number: 10,
//   totalResults: 25,
// };

// export const SampleRecipe = {
//   vegetarian: false,
//   vegan: false,
//   glutenFree: false,
//   dairyFree: false,
//   veryHealthy: false,
//   cheap: false,
//   veryPopular: false,
//   sustainable: false,
//   weightWatcherSmartPoints: 17,
//   gaps: "no",
//   lowFodmap: false,
//   aggregateLikes: 209,
//   spoonacularScore: 83,
//   healthScore: 19,
//   creditsText: "Full Belly Sisters",
//   license: "CC BY-SA 3.0",
//   sourceName: "Full Belly Sisters",
//   pricePerServing: 163.15,
//   extendedIngredients: [
//     {
//       id: 1001,
//       aisle: "Milk, Eggs, Other Dairy",
//       image: "butter-sliced.jpg",
//       consistency: "solid",
//       name: "butter",
//       nameClean: "butter",
//       original: "1 tbsp butter",
//       originalString: "1 tbsp butter",
//       originalName: "butter",
//       amount: 1,
//       unit: "tbsp",
//       meta: [],
//       metaInformation: [],
//       measures: {
//         us: {
//           amount: 1,
//           unitShort: "Tbsp",
//           unitLong: "Tbsp",
//         },
//         metric: {
//           amount: 1,
//           unitShort: "Tbsp",
//           unitLong: "Tbsp",
//         },
//       },
//     },
//     {
//       id: 10011135,
//       aisle: "Produce",
//       image: "cauliflower.jpg",
//       consistency: "solid",
//       name: "cauliflower florets",
//       nameClean: "cauliflower florets",
//       original:
//         "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
//       originalString:
//         "about 2 cups frozen cauliflower florets, thawed, cut into bite-sized pieces",
//       originalName:
//         "about frozen cauliflower florets, thawed, cut into bite-sized pieces",
//       amount: 2,
//       unit: "cups",
//       meta: ["frozen", "thawed", "cut into bite-sized pieces"],
//       metaInformation: ["frozen", "thawed", "cut into bite-sized pieces"],
//       measures: {
//         us: {
//           amount: 2,
//           unitShort: "cups",
//           unitLong: "cups",
//         },
//         metric: {
//           amount: 473.176,
//           unitShort: "ml",
//           unitLong: "milliliters",
//         },
//       },
//     },
//     {
//       id: 1041009,
//       aisle: "Cheese",
//       image: "cheddar-cheese.png",
//       consistency: "solid",
//       name: "cheese",
//       nameClean: "cheese",
//       original: "2 tbsp grated cheese (I used romano)",
//       originalString: "2 tbsp grated cheese (I used romano)",
//       originalName: "grated cheese (I used romano)",
//       amount: 2,
//       unit: "tbsp",
//       meta: ["grated", "(I used romano)"],
//       metaInformation: ["grated", "(I used romano)"],
//       measures: {
//         us: {
//           amount: 2,
//           unitShort: "Tbsps",
//           unitLong: "Tbsps",
//         },
//         metric: {
//           amount: 2,
//           unitShort: "Tbsps",
//           unitLong: "Tbsps",
//         },
//       },
//     },
//     {
//       id: 1034053,
//       aisle: "Oil, Vinegar, Salad Dressing",
//       image: "olive-oil.jpg",
//       consistency: "liquid",
//       name: "extra virgin olive oil",
//       nameClean: "extra virgin olive oil",
//       original: "1-2 tbsp extra virgin olive oil",
//       originalString: "1-2 tbsp extra virgin olive oil",
//       originalName: "extra virgin olive oil",
//       amount: 1,
//       unit: "tbsp",
//       meta: [],
//       metaInformation: [],
//       measures: {
//         us: {
//           amount: 1,
//           unitShort: "Tbsp",
//           unitLong: "Tbsp",
//         },
//         metric: {
//           amount: 1,
//           unitShort: "Tbsp",
//           unitLong: "Tbsp",
//         },
//       },
//     },
//     {
//       id: 11215,
//       aisle: "Produce",
//       image: "garlic.png",
//       consistency: "solid",
//       name: "garlic",
//       nameClean: "garlic",
//       original: "5-6 cloves garlic",
//       originalString: "5-6 cloves garlic",
//       originalName: "garlic",
//       amount: 5,
//       unit: "cloves",
//       meta: [],
//       metaInformation: [],
//       measures: {
//         us: {
//           amount: 5,
//           unitShort: "cloves",
//           unitLong: "cloves",
//         },
//         metric: {
//           amount: 5,
//           unitShort: "cloves",
//           unitLong: "cloves",
//         },
//       },
//     },
//     {
//       id: 20420,
//       aisle: "Pasta and Rice",
//       image: "fusilli.jpg",
//       consistency: "solid",
//       name: "pasta",
//       nameClean: "pasta",
//       original: "6-8 ounces pasta (I used linguine)",
//       originalString: "6-8 ounces pasta (I used linguine)",
//       originalName: "pasta (I used linguine)",
//       amount: 6,
//       unit: "ounces",
//       meta: ["(I used linguine)"],
//       metaInformation: ["(I used linguine)"],
//       measures: {
//         us: {
//           amount: 6,
//           unitShort: "oz",
//           unitLong: "ounces",
//         },
//         metric: {
//           amount: 170.097,
//           unitShort: "g",
//           unitLong: "grams",
//         },
//       },
//     },
//     {
//       id: 1032009,
//       aisle: "Spices and Seasonings",
//       image: "red-pepper-flakes.jpg",
//       consistency: "solid",
//       name: "red pepper flakes",
//       nameClean: "red pepper flakes",
//       original: "couple of pinches red pepper flakes, optional",
//       originalString: "couple of pinches red pepper flakes, optional",
//       originalName: "couple of red pepper flakes, optional",
//       amount: 2,
//       unit: "pinches",
//       meta: ["red"],
//       metaInformation: ["red"],
//       measures: {
//         us: {
//           amount: 2,
//           unitShort: "pinches",
//           unitLong: "pinches",
//         },
//         metric: {
//           amount: 2,
//           unitShort: "pinches",
//           unitLong: "pinches",
//         },
//       },
//     },
//     {
//       id: 1102047,
//       aisle: "Spices and Seasonings",
//       image: "salt-and-pepper.jpg",
//       consistency: "solid",
//       name: "salt and pepper",
//       nameClean: "salt and pepper",
//       original: "salt and pepper, to taste",
//       originalString: "salt and pepper, to taste",
//       originalName: "salt and pepper, to taste",
//       amount: 2,
//       unit: "servings",
//       meta: ["to taste"],
//       metaInformation: ["to taste"],
//       measures: {
//         us: {
//           amount: 2,
//           unitShort: "servings",
//           unitLong: "servings",
//         },
//         metric: {
//           amount: 2,
//           unitShort: "servings",
//           unitLong: "servings",
//         },
//       },
//     },
//     {
//       id: 11291,
//       aisle: "Produce",
//       image: "spring-onions.jpg",
//       consistency: "solid",
//       name: "scallions",
//       nameClean: "spring onions",
//       original: "3 scallions, chopped, white and green parts separated",
//       originalString: "3 scallions, chopped, white and green parts separated",
//       originalName: "scallions, chopped, white and green parts separated",
//       amount: 3,
//       unit: "",
//       meta: ["white", "green", "separated", "chopped"],
//       metaInformation: ["white", "green", "separated", "chopped"],
//       measures: {
//         us: {
//           amount: 3,
//           unitShort: "",
//           unitLong: "",
//         },
//         metric: {
//           amount: 3,
//           unitShort: "",
//           unitLong: "",
//         },
//       },
//     },
//     {
//       id: 14106,
//       aisle: "Alcoholic Beverages",
//       image: "white-wine.jpg",
//       consistency: "liquid",
//       name: "white wine",
//       nameClean: "dry white wine",
//       original: "2-3 tbsp white wine",
//       originalString: "2-3 tbsp white wine",
//       originalName: "white wine",
//       amount: 2,
//       unit: "tbsp",
//       meta: ["white"],
//       metaInformation: ["white"],
//       measures: {
//         us: {
//           amount: 2,
//           unitShort: "Tbsps",
//           unitLong: "Tbsps",
//         },
//         metric: {
//           amount: 2,
//           unitShort: "Tbsps",
//           unitLong: "Tbsps",
//         },
//       },
//     },
//     {
//       id: 99025,
//       aisle: "Pasta and Rice",
//       image: "breadcrumbs.jpg",
//       consistency: "solid",
//       name: "whole wheat bread crumbs",
//       nameClean: "whole wheat breadcrumbs",
//       original: "1/4 cup whole wheat bread crumbs (I used panko)",
//       originalString: "1/4 cup whole wheat bread crumbs (I used panko)",
//       originalName: "whole wheat bread crumbs (I used panko)",
//       amount: 0.25,
//       unit: "cup",
//       meta: ["whole wheat", "(I used panko)"],
//       metaInformation: ["whole wheat", "(I used panko)"],
//       measures: {
//         us: {
//           amount: 0.25,
//           unitShort: "cups",
//           unitLong: "cups",
//         },
//         metric: {
//           amount: 59.147,
//           unitShort: "ml",
//           unitLong: "milliliters",
//         },
//       },
//     },
//   ],
//   id: 716429,
//   title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
//   readyInMinutes: 45,
//   servings: 2,
//   sourceUrl:
//     "http://fullbellysisters.blogspot.com/2012/06/pasta-with-garlic-scallions-cauliflower.html",
//   image: "https://spoonacular.com/recipeImages/716429-556x370.jpg",
//   imageType: "jpg",
//   summary:
//     'Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs might be just the main course you are searching for. This recipe makes 2 servings with <b>636 calories</b>, <b>21g of protein</b>, and <b>20g of fat</b> each. For <b>$1.83 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes about <b>45 minutes</b>. This recipe is liked by 209 foodies and cooks. If you have pasta, salt and pepper, cheese, and a few other ingredients on hand, you can make it. To use up the extra virgin olive oil you could follow this main course with the <a href="https://spoonacular.com/recipes/peach-crisp-healthy-crisp-for-breakfast-487698">Peach Crisp: Healthy Crisp for Breakfast</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 86%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/cauliflower-gratin-with-garlic-breadcrumbs-318375">Cauliflower Gratin with Garlic Breadcrumbs</a>, <a href="https://spoonacular.com/recipes/pasta-with-cauliflower-sausage-breadcrumbs-30437">Pasta With Cauliflower, Sausage, & Breadcrumbs</a>, and <a href="https://spoonacular.com/recipes/pasta-with-roasted-cauliflower-parsley-and-breadcrumbs-30738">Pasta With Roasted Cauliflower, Parsley, And Breadcrumbs</a> for similar recipes.',
//   cuisines: [],
//   dishTypes: ["lunch", "main course", "main dish", "dinner"],
//   diets: [],
//   occasions: [],
//   winePairing: {
//     pairedWines: [],
//     pairingText:
//       "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
//     productMatches: [],
//   },
//   instructions: "",
//   analyzedInstructions: [],
//   originalId: null,
//   spoonacularSourceUrl:
//     "https://spoonacular.com/pasta-with-garlic-scallions-cauliflower-breadcrumbs-716429",
// };
